language: java
sudo: false
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: ffb23d34-3a99-426f-a139-80d703cbd614
  app: travis-company-app
  on:
    repo: lukaszziobro89/travis-company-app